[package]
name = "derive_enum_rotate"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.53" }
quote = "1.0.35"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.79"